# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install project dependencies
        run: npm install --ignore-scripts

      - name: Check for linting errors
        run: npm run lint

      - name: Build extension
        run: npm run build:ext
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Pack extension
        run: npx vsce package --no-dependencies --out arduino-vscode-ide.vsix

      - name: Publish extension VSIX as artifact
        uses: actions/upload-artifact@v4
        with:
          name: VS Code extension VSIX (${{ matrix.os }})
          path: arduino-vscode-ide.vsix


      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test --silent
